version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    volumes:
      - ./web/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ./web/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: mongo:latest
    container_name: mongo
    #environment:
      #- MONGODB_USER=admin
      #- MONGODB_PASS=123456
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./web/mongo/db:/data/db #数据文件挂载
      - ./web/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017
  redis:
    image: redis:4
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./web/redis/data:/data"
    command: ["redis-server", "--appendonly", "yes"]
